[package]
name = "wasm2048"
version = "0.0.1"
edition = "2021"

[lib]

[workspace]
members = ["modules/*"]

[features]
default = ["engine"]
engine = ["dep:wasmer"]

[dependencies]
wasmer = { version = "2.3.0", optional = true }